name: Build and Push Backend

on:
  push:
    branches: [ develop ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3


    - name: Debug Secrets
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"


    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

    - name: Build and push image
      run: |
        docker build -t jthort00/skynet-backend:latest .
        docker push jthort00/skynet-backend:latest
      
