name: Build, Lint and Package Backend

on:
  push:
    branches: [ "main", "develop", "chore/*" ]
  pull_request:
    branches: [ "main", "develop", "chore/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build Docker image
        run: docker build -t backend-app .
